### ISSUE TITLE
I can't find my ScreenRecording in Aves. 

### ISSUE THREAD

**Issue by Distant-User** [deckerst/aves#619]
Answer to your question:
 I can't find them in the app. 

Hello there, I'm **Win2** from Google PlayStore.

Here's the problem... 

The phone I'm using is **Infinix Note 12 G96**. 

I screen recorded a game I'm playing and when I saved it, the record doesn't appear in the gallery.
I went to my phone's file manager and opened the record there with Aves. It opened and I was able to play it, but it still doesn't appear in the app.

It's not in the "Collection", it's not in the "Video" tag either, and there's no Album for it in the app.

This happened before, months before but I decided to let it slide since it's not that much of a problem and I can use my phone's built-in gallery, and I figured that it will probably be fixed in the next update. 

![Screenshot_20230430-115803.jpg](https://user-images.githubusercontent.com/132182115/235334876-bf9ce396-d719-4d6e-a8fd-8ae6ef157174.jpg)

![Screenshot_20230430-115754.jpg](https://user-images.githubusercontent.com/132182115/235334877-cca2f45c-619f-491b-8bce-b2930a2ac627.jpg)

![Screenshot_20230430-115848.jpg](https://user-images.githubusercontent.com/132182115/235334880-436bc20e-905c-4381-a8b7-554f58f6d267.jpg)

![Screenshot_20230430-115841.jpg](https://user-images.githubusercontent.com/132182115/235334881-70136710-6a84-4650-8267-cceca163d4ea.jpg)

![Screenshot_20230430-115757.jpg](https://user-images.githubusercontent.com/132182115/235334879-4e626366-0b7e-44a9-9361-8c64b80a5b7f.jpg)

![Screenshot_20230430-115829.jpg](https://user-images.githubusercontent.com/132182115/235334878-da6074e0-e7f6-40d4-847c-82e1d0850f6a.jpg)

**Comment by deckerst** [comment]
Thanks for following up.

Usually, when media does not appear in Aves, it is for one of these reasons:
- there's a ".nomedia" file next to the media, so the system Media Store doesn't register them
- the system Media Store hasn't registered them yet but it will eventually, it's just a delay (often happens on older devices, or when files are created by badly written apps)
- the items are hidden within Aves via one of the filters in `Settings` > `Privacy` > `Hidden filters`.

Could you double-check your issue is not for one of these reasons?

Could you please follow instructions in the app `About` > `Bug Report` section and attach here your logs and system info? Also, do you use a custom ROM?

**Comment by Distant-User** [comment]
Follow Up:

Looks like the reason is the 3rd reason.

I don't remember hiding the filter and I'm sure I didn't do it on purpose,
so I must have accidentally hidden it / clicked on it along with the other
tags I'd hidden before.

Thanks for the help! I'm really glad since there's been some apps where the
developer doesn't respond haha.

and no, I'm not using custom ROM.

**Comment by deckerst** [comment]
I'm glad the mystery is solved!

**Comment by Distant-User** [comment]
I'm unable to access the videos and pictures that's on my SD Card.

I already check the Hidden Items and it wasn't there.
I tried opening the videos through File Manager, I'm able to view it but it
still isn't displayed on the app.

Is there a solution or reason for this?

**Comment by deckerst** [comment]
@Distant-User I can only point you to what I've mentioned [above](https://github.com/deckerst/aves/issues/619#issuecomment-1528961305). If you say it's not hidden at the app level, maybe it's the Media Store that is not updated. How did you get that media on your SD card? Was it a long time ago?
